#! /usr/bin/env python

import os

def configure(conf):
    conf.load('waf_dynamo')
    conf.load('java')

def build(bld):
    bld.load('java')

    bld.program(features = 'cxx test',
                    includes = '. ..',
                    use = 'DLIB PROFILE model',
                    target = 'test_model',
                    source = 'test_model.cpp')

    classpath = ['%s/src/modelimporter.jar' % bld.bldnode.abspath(),
                 '%s/ext/share/java/junit-4.6.jar' % bld.env.DYNAMO_HOME]
    classpath = os.pathsep.join(classpath)

    bld(features='javac seq',
        classpath=classpath,
        srcdir='java',
        outdir='java')

    bld.env["JAVACFLAGS"] = '-g'.split()

    bld(features='jar seq test',
        basedir ='java',
        destfile ='test_modelc.jar',
        name = 'test_modelc',
        classpath=classpath,
        java_library_paths=['%s/src' % bld.bldnode.abspath()],
        mainclass='com.dynamo.bob.pipeline.TestModelc')
