#! /usr/bin/env python
import os
import waflib.Options
from waf_dynamo import platform_graphics_libs, platform_graphics_symbols

def configure(conf):
    pass

def build(bld):
    graphics_lib = ['DMGLFW'] + platform_graphics_libs(bld.env['PLATFORM'])
    exported_symbols = platform_graphics_symbols(bld.env['PLATFORM'])

    b = bld.program(features         = 'c cprogram cxx',
                    use              = ['SOCKET','HID','INPUT','DDF','DLIB','PROFILE_NULL','PLATFORM','DMGLFW','X '] + graphics_lib,
                    exported_symbols = exported_symbols,
                    source           = 'main.cpp',
                    target           = 'gdc')

    if bld.env.PLATFORM in ('x86_64-macos','arm64-macos',):
        b.env.append_value('LINKFLAGS', ['-framework', 'Metal', '-framework', 'Foundation', '-framework', 'IOSurface'])
