#! /usr/bin/env python

import os
from waf_dynamo import dmsdk_add_files
from waflib.Options import options

import gen_java

def configure(conf):
    if not conf.env.IS_TARGET_DESKTOP:
        print("Skipping build of modelc for non host platform")
        return

    conf.load('java')

    dynamo_home = conf.env.DYNAMO_HOME
    includes = [os.getcwd(),
                os.path.join(dynamo_home, 'sdk', 'include')]

    def make_path(path):
        cwd = os.getcwd()
        script_dir = conf.path.abspath()
        path = os.path.normpath(os.path.join(script_dir, path))
        if not os.path.exists(path):
            os.makedirs(path)
        return os.path.relpath(path, cwd)

    gen_java.generate(header_path   = make_path('./modelimporter.h'),
                     namespace      = 'dmModelImporter',
                     java_namespace = 'ModelImporter',
                     package_name   = 'com.dynamo.bob.pipeline',
                     includes       = includes,
                     java_outdir    = make_path('./java'),
                     jni_outdir     = make_path('./jni'))


def build(bld):
    # We only need this library in the editor and bob
    if not bld.env.IS_TARGET_DESKTOP:
        print("Skipping build of modelc for non host platform")
        return

    modelc_sources = bld.path.ant_glob("*.cpp")
    modelc_sources.extend(bld.path.ant_glob("jni/**/*.cpp"))

    # really only used for the unit tests
    model = bld.stlib(features = 'c cxx',
                      includes = ['.', './model'],
                      use       = 'JDK JNI',
                      source = modelc_sources,
                      target = 'model')

    # Used by bob.jar + editor
    bld(features = 'c cxx cshlib skip_asan extract_symbols',
       includes = model.includes,
       uselib = 'DLIB_NOASAN APP PROFILE_NULL_NOASAN JDK JNI_NOASAN',
       source = modelc_sources,
       target = 'modelc_shared')

    classpath = []

    bld(features='javac seq',
        classpath=classpath,
        srcdir='java',
        outdir='java')

    bld.env["JAVACFLAGS"] = '-g -source 1.7 -target 1.7'.split()

    bld(features='jar seq',
        basedir='java',
        destfile='modelimporter.jar')

    bld.install_files('${PREFIX}/share/java', 'modelimporter.jar')

    if not options.skip_build_tests:
        bld.recurse('test')
